trigger PCWorkflowTrigger on Workflow__c (after insert, before insert, before update, after update, after delete,before delete) { 
    //after triggers 
    if (Trigger.isAfter) { 

        /* 
            This part creates first group tasks when new object is created 
        */ 
        if(Trigger.isInsert) {
            FSTR.ProcessComposerExecution.CreateSteps(Trigger.new);     
        }
        if(Trigger.isUpdate){
            FSTR.RBPExecution.AfterObjectUpdate(Trigger.old, Trigger.new);        
            FSTR.ProcessComposerExecution.CreateStepsOnUpdate(Trigger.old, Trigger.newMap); 
       } 
    } 


    /* 
    The trigger is fired before creation of new object 
    */ 
    if (Trigger.isBefore) { 
        if (Trigger.isInsert || Trigger.isUpdate){ 
            if(Trigger.isInsert){ 
                FSTR.ProcessComposerExecution.DetermineBusiness(Trigger.new); 
                for(Workflow__c newRec : Trigger.new) { 
                    //set status to open 
                    newRec.Status__c = 'Open'; 
                    // sync the custom workflow name with PC custom field
                    newRec.Subject__c = newRec.Workflow_CustomName__c;
                }
            } 
            FSTR.ProcessComposerExecution.DetermineDefinition(Trigger.new); 
        } 
        else if(Trigger.isDelete){ 
            for(Workflow__c delRec : Trigger.Old) { 
                if(delRec.Recurring_Business_Process__c != null) 
                    delRec.addError('You cannot delete a Workflow record that was generated by a Recurring Business Process.'); 
            }
        }   
    } 
}