/*****************************************************************************************
Class Name: ApplicationException
Purpose: This class for throwing custom excetion errors
******************************************************************************************
Version         DateModified         ModifiedBy               Change
1.0             13/02/2017           Mohit Goyal              Initial Development
******************************************************************************************/

public class ApplicationException extends Exception {
    //extending standard exception class 
}