/*****************************************************************************************
Class Name: GBSConstants
Purpose: Class for maintaining constants used in the GBS app
******************************************************************************************
Version        	DateModified         	ModifiedBy               	Change
1.0             26/04/2018           	Jay                    		Initial Development
******************************************************************************************/

public class GBSConstants {
    
    public static final string LICENSEECONTACT = 'GBS Licensee'; 
    public static final string AGENTCONTACT = 'GBS Agent'; 
    public static final string FACTORYCONTACT = 'GBS Factory';     
    public static final string TRADEOFFICECONTACT = 'GBS Trade Office'; 
    public static final string AUDITFIRMCONTACT = 'GBS Audit Firm';
    public static final string DEALMAKERCONTACT = 'GBS Dealmaker';    
    public static final string AGENTACCOUNT = 'GBS Agent';    
    public static final string LICENSEEACCOUNT = 'GBS Licensee';
    public static final string GBSDEFAULTACCOUNT = 'GBS Default';
    public static final string DEFAULTFACTORYACCOUNT = 'Factory Default'; 
    public static final string DEFAULTTRADEOFFICEACCOUNT = 'Trade Office Default';
    public static final string DEFAULTAUDITFIRMACCOUNT = 'Audit Firm Default';
    public static final string DEFAULTDEALMAKERACCOUNT = 'Dealmaker Default';    
    public static final string GBSPARTNEREXEMPTIONWORKFLOW = 'Partner Exemption';
    public static final string GBSPARTNEREXEMPTIONAPPROVED = 'Exemption Approved';
    public static final string GBSPARTNEREXEMPTIONAPPROVEDCONDITIONALLY = 'Exemption Approved - Conditionally';
    public static final string GBSCONTRACTSTATUSPENDING = 'Contract Pending';
    public static final string GBSCONTRACTSTATUSOUTFORSIGNATURE ='Out for Signature';
    public static final string GBSCONTRACTSTATUSINFORSIGNATURE ='In for Signature';
    public static final string GBSCONTRACTSTATUSFULLYEXECUTED ='Fully Executed';
    public static final string GBSCONTRACTSTATUSACTIVE ='Active'; 
    public static final string GBSLMSNOAPPROVEDFACTORIES = 'No Approved Factories';
    public static final string GBSNOLMSSUBMITTED = 'No LMS\'s Submitted';
    public static final string GBSLMSPRIMARYFACTORY = 'Primary Factory';
    public static final string GBSLMSDISTRIBUTIONONLY = 'Distribution Only';
    public static final string GBSLMSSUBCONTRACTEDFACTORY = 'Subcontracted Factory';
    public static final string GBSTaskRecordType = 'GBS Task';
    //added for GBS-762
    public static final string GBSCONTRACTSTATUSTERMINATED ='Terminated';
    public static final string GBSCONTRACTSTATUSCANCELLED ='Cancelled';
    public static final string GBSCONTRACTSTATUSEXPIRED ='Expired';
    //added for GBS-632
    public static final string GBSPARTNEREXEMPTIONDISAPPROVED = 'Exemption Disapproved';     
    
}